name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Podman and Run on Fedora 43
      run: |
        sudo apt-get update && sudo apt-get install -y podman
        podman run --rm -v "$PWD:/work" -w "/work" fedorapython/fedora-python-tox bash -c '
          dnf -y install make uv python3-cairo cairo-gobject-devel cairo-devel
          make test
        '
